# Site settings
title: "George's Blog" 
motto: Stop overthinking... 
description: > # this means to ignore newlines until "baseurl:"
 This is my blog, where I share with you anything I have in mind ... 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sarris.uk" # the base hostname & protocol for your site
twitter_username: gsarristz
github_username:  gsarristz

# Build settings
markdown: kramdown
